name: Run Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          npm install
          python -m pip install --upgrade pip
          pip install pytest
          

      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps
          pip install playwright
          playwright install

      - name: Run tests
        run: |
          npm test
          pytest tests/
